// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwpvgbhjjcxclswslnbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cHZnYmhqamN4Y2xzd3NsbmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTk1NjIsImV4cCI6MjA2MTc3NTU2Mn0.KnsdaSc-W0qK5tsYi9FbqH-db7q_IOtvaxw7QSR3Wrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'pochimuchka',
  },
});